### ISSUE TITLE
Update the mailto address for the Contact Us hyperlink

### ISSUE THREAD

**Issue by beckysteck** [uwrit/kpmp_ds#1]
In the blue text box on the https://welcome.kpmp.org/shibds/ page, there is a "Contact us for assistance" sentence that includes a mailto link for info@kpmp.org

- [x] We'd like that mailto link changed to this instead: admin@kpmp.org

![image](https://user-images.githubusercontent.com/8238728/68970520-73b5f100-07b5-11ea-91f6-92acca8f6048.png)

**Comment by beckysteck** [comment]
Hi @mh2727 ! Can you let me know how I can test this? Is there a link you can send me to a QA environment? Thanks!

**Comment by mh2727** [comment]
Hi. I'm using GitHub pages as a temporary way to test our code. Here's the link https://uwrit.github.io/kpmp_ds/

**Comment by beckysteck** [comment]
This passes QA (checked in Chrome, FF, and IE), but I don't have write-access to the repo so I can't change the label @mh2727

**Comment by beckysteck** [comment]
Looks good - please close this issue @mh2727 !
