### ISSUE TITLE
Remove scrollbars that appear in unopened drop-down box on Chrome and IE

### ISSUE THREAD

**Issue by beckysteck** [uwrit/kpmp_ds#2]
- [x] If you're accessing the https://welcome.kpmp.org/shibds/ page from Chrome or IE (but not Firefox) on a Windows machine, a weird scroll bar appears (see screenshot).

Please see if this can be removed. (Keep in mind this is a relatively low-priority issue. If you find it's a real beast to fix, we can likely live with it.)

![image](https://user-images.githubusercontent.com/8238728/68971108-cc39be00-07b6-11ea-9e35-63e3a7e7c866.png)

**Comment by mh2727** [comment]
Once again, please use this link to test the changes: https://uwrit.github.io/kpmp_ds/

**Comment by beckysteck** [comment]
This passes QA (checked in Chrome, FF, and IE), but I don't have write-access to the repo so I can't change the label @mh2727

**Comment by beckysteck** [comment]
This looks good in production @mh2727 . Feel free to close this issue.
