### ISSUE TITLE
Make Welcome page respond better in desktop, mobile, and tablet views

### ISSUE THREAD

**Issue by mrose1202** [uwrit/kpmp_ds#4]
See the attached screenshots for examples of how the info box and page is responding poorly on desktop, tablet, and mobile views. 

![welcome_tablet-view](https://user-images.githubusercontent.com/28305264/69159666-4b303e80-0ab6-11ea-84da-fac562795103.PNG)
![welcome_desktop-lg-screen-view](https://user-images.githubusercontent.com/28305264/69159667-4b303e80-0ab6-11ea-810c-5fa07962303c.png)
![welcome_mobile-view](https://user-images.githubusercontent.com/28305264/69159669-4bc8d500-0ab6-11ea-86eb-51b5e62ba82f.PNG)

Michael Rose
rosemi@umich.edu

**Comment by mh2727** [comment]
I have addressed these issues. Here is the link to test it: https://uwrit.github.io/kpmp_ds/

The changes should work on mobile, tablet, and web browsers.

**Comment by mrose1202** [comment]
HI Mahadi -- I have to fail this. Sorry for not being more implicit before. This is the desired behavior and layout: (I did a quick screen grab and moved things around for this example.)

1) The NetID info section is meant to be displayed like this in "desktop" view at 1024 px width:
![image](https://user-images.githubusercontent.com/28305264/71838275-6cf57d00-3086-11ea-9b3e-503bdfe63e10.png)

2) In an extended width view, the info section should retain its position:
![image](https://user-images.githubusercontent.com/28305264/71838402-b8a82680-3086-11ea-90ab-f33b501fe29c.png)

3) In mobile/tablet view, the info section should stack just below the "remember me" check box:
 
![image](https://user-images.githubusercontent.com/28305264/71838526-045ad000-3087-11ea-9d48-d54dcd1cef6a.png)

Hope this helps. Email me if you have questions. (rosemi@umich.edu)

**Comment by mrose1202** [comment]
@mh2727 : finished my QA. See my comment above. Thanks!

**Comment by mh2727** [comment]
@mrose1202 : Updates have been made. Let me know if these pass. Thank you. https://uwrit.github.io/kpmp_ds/

**Comment by mrose1202** [comment]
@mh2727 UX/QA: Pass -- Ship it! :)

**Comment by beckysteck** [comment]
@mh2727 This looks good to us. Feel free to close this issue now. (We don't have that ability.)
